version: '3.4'

services:
  db:
    image: postgres
    environment: 
      - POSTGRES_DB=blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  pga:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=maciej.nachtygal@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports: 
      - "5050:80"
    depends_on: 
      - db
  django:
    build: .
    command: python manage.py makemigrations
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    environment: 
      - DOCKER=1
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SECRET_KEY=q(a-51l-1#7@s5725y+%630e5mr5jjuu4t6=m28d2go9&=6_
    volumes:
      - ./blog:/app
    ports:
      - "8000:8000"
    depends_on: 
      - db
