version: '3.4'

services:
  db:
    image: postgres
    environment: 
      - POSTGRES_DB=blogdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  pga:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=maciej.nachtygal@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports: 
      - "5050:80"
    depends_on: 
      - db
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment: 
      - DATABASE_URL=postgres://postgres:postgres@db:5432/blogdb
    volumes:
      - ./blog:/app
    ports:
      - "8000:8000"
    depends_on: 
      - db
