name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Django tests
        run: |
          export PATH="$PATH:/home/runner/.local/bin"
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel
          python3 -m pip install -r requirements.txt         
          python3 manage.py makemigrations
          python3 manage.py migrate
          python3 manage.py test
