name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Django tests
        run: |
          apt-get install python3-setuptools
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          python3 manage.py makemigrations
          python3 manage.py migrate
          python3 manage.py test
