name: Deployment

on:
  push:
    branches: [ test ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Sync
      env:
        DEST: "${{secrets.HOSTING_USER}}@${{secrets.HOSTING}}:~/domain/notatnik.macieyn.mduser.net/public_python"
      run: |
        echo "${{secrets.DEPLOY_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -chav --delete \
          -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
          --exclude /deploy_key \
          --exclude /.git/ \
          --exclude /.github/ \
           ./ ${{env.DEST}}
           
    - name: Run migrations and collect static files via SSH
      uses: appleboy/ssh-action@master
      with:
        host: s48.mydevil.net
        username: macieyn
        key: ${{ secrets.DEPLOY_KEY}}
        port: 22
        script: |
          cd ~/domains/notatnik.macieyn.usermd.net/public_python
          source ~/.virtualenvs/junior/bin/activate
          python3 manage.py makemigrations
          python3 manage.py migrate
          python3 manage.py collectstatic --clear
